version: "3"
services:

  api:
    image: co.uk.deep3/medus-labs-api
    ports:
      - "8080:8080"
    environment:

      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
  ui:
    image: medus-labs-ui
    ports:
      - "80:80"
    depends_on:
      - api